# Generated by Django 3.1 on 2020-08-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.supermercado')),
            ],
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
                ('preco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.preco')),
                ('produtos', models.ManyToManyField(to='principal.Produto')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='principal.supermercado')),
            ],
        ),
    ]
